config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.fair.metadata-uses-cessda-pids:
      branch: main
      repo: https://github.com/cessda/cessda.fair.metadata-uses-cessda-pids.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-pids git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cream-uakari.sh
        container: qc.acc_bluesy-purple-guppy
  QC.Doc:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-pids find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-malachite-capuchin.sh
        container: qc.doc_snoopy-cinnamon-ocelot
      github.com/cessda/cessda.fair.metadata-uses-cessda-pids git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-amethyst-wolfhound.sh
        container: qc.doc_skanky-myrtle-akita
      github.com/cessda/cessda.fair.metadata-uses-cessda-pids markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-red-pig.sh
        container: qc.doc_slimy-cream-devil
  QC.Lic:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-pids licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-lime-fly.sh
        container: qc.lic_nippy-pink-retriever
  QC.Met:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-pids cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-firebrick-ray.sh
        container: qc.met_ready-salmon-monkey
  QC.Sty:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-pids checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-seashell-bordeaux.sh
        container: qc.sty_nerdy-tomato-goat
      github.com/cessda/cessda.fair.metadata-uses-cessda-pids hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-lilac-swan.sh
        container: qc.sty_hasty-heliotrope-albatross
  QC.Ver:
    repos:
      github.com/cessda/cessda.fair.metadata-uses-cessda-pids get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-alizarin-panda.sh
        container: qc.ver_fuzzy-cobalt-magpie
timeout: 5400
